apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sd-datasets

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.dataset.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sd-models

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.model.storage }}